"use strict";

const VIDEO_TESTE = "https://www.youtube.com/embed/r9AoQVkUUvU";
const TOTAL_VIDAS = 3;

const questoesBase = [
  {id:"vis-01",topico:"Raiz quadrada",nivel:1,contexto:"A escola construirá uma praça quadrada com 64 m² de área.",pergunta:"Quanto deve medir cada lado da praça?",tipo:"grade",visual:{linhas:8,colunas:8,tema:"grama"},descricao:"Planta de uma praça quadrada dividida em 64 partes iguais, organizadas em 8 linhas e 8 colunas.",alternativas:["8 metros","16 metros","32 metros","64 metros"],correta:"8 metros",dica:"O lado deve ser um número que, multiplicado por ele mesmo, resulte em 64.",explicacao:"Como 8 × 8 = 64, temos √64 = 8. Cada lado da praça deve medir 8 metros."},
  {id:"vis-02",topico:"Formação de quadrados",nivel:1,contexto:"Uma turma organizou 49 azulejos formando um mosaico quadrado.",pergunta:"Quantos azulejos ficaram em cada fileira?",tipo:"grade",visual:{linhas:7,colunas:7,tema:"azul"},descricao:"Mosaico quadrado com 49 azulejos, distribuídos em 7 linhas e 7 colunas.",alternativas:["7 azulejos","6 azulejos","14 azulejos","49 azulejos"],correta:"7 azulejos",dica:"Conte quantas linhas e colunas formam o quadrado.",explicacao:"O mosaico possui 7 linhas com 7 azulejos: 7 × 7 = 49. Portanto, √49 = 7."},
  {id:"vis-03",topico:"Raiz cúbica",nivel:1,contexto:"Uma embalagem cúbica comporta 27 blocos iguais, organizados em camadas.",pergunta:"Quantos blocos há em cada dimensão da embalagem?",tipo:"cubo",visual:{lado:3},descricao:"Cubo formado por 27 blocos: 3 de largura, 3 de altura e 3 de profundidade.",alternativas:["3 blocos","6 blocos","9 blocos","27 blocos"],correta:"3 blocos",dica:"Procure o número que aparece três vezes na multiplicação que resulta em 27.",explicacao:"3 × 3 × 3 = 27. Assim, ∛27 = 3 e existem 3 blocos em cada dimensão."},
  {id:"vis-04",topico:"Raiz cúbica",nivel:1,contexto:"Uma caixa cúbica possui volume de 64 cm³.",pergunta:"Qual é a medida de cada aresta da caixa?",tipo:"cubo",visual:{lado:4},descricao:"Representação de uma caixa cúbica dividida em 4 partes em cada direção.",alternativas:["4 centímetros","8 centímetros","16 centímetros","32 centímetros"],correta:"4 centímetros",dica:"A aresta é multiplicada por ela mesma três vezes.",explicacao:"4 × 4 × 4 = 64. Portanto, ∛64 = 4 e cada aresta mede 4 centímetros."},
  {id:"vis-05",topico:"Elementos da raiz",nivel:1,contexto:"Lia encontrou a expressão ∛125 = 5 em uma atividade.",pergunta:"Qual parte indica que a raiz é cúbica?",tipo:"expressao",visual:{partes:[{texto:"3",rotulo:"índice",destaque:true},{texto:"√",rotulo:"radical"},{texto:"125",rotulo:"radicando"},{texto:"= 5",rotulo:"raiz"}]},descricao:"Expressão raiz cúbica de 125 igual a 5, com o índice 3 destacado.",alternativas:["O índice 3","O radicando 125","A raiz 5","O sinal de igualdade"],correta:"O índice 3",dica:"Observe o número pequeno colocado junto ao radical.",explicacao:"O índice 3 informa que buscamos um número multiplicado por ele mesmo três vezes."},
  {id:"vis-06",topico:"Raiz exata",nivel:1,contexto:"Um jardim quadrado será dividido em 81 canteiros iguais.",pergunta:"Quantos canteiros haverá em cada lado do jardim?",tipo:"grade",visual:{linhas:9,colunas:9,tema:"grama"},descricao:"Jardim quadrado com 81 canteiros organizados em 9 linhas e 9 colunas.",alternativas:["9 canteiros","8 canteiros","18 canteiros","27 canteiros"],correta:"9 canteiros",dica:"Qual número ao quadrado resulta em 81?",explicacao:"9 × 9 = 81. Portanto, √81 = 9 e cada lado terá 9 canteiros."},
  {id:"vis-07",topico:"Caso com zero",nivel:1,contexto:"Uma moldura quadrada possui área igual a zero.",pergunta:"Qual é a medida matemática de seu lado?",tipo:"objetos",visual:{icone:"□",quantidade:1,colunas:1,vazio:true},descricao:"Contorno de um quadrado sem área preenchida.",alternativas:["0","1","2","Não existe"],correta:"0",dica:"Zero multiplicado por zero continua sendo zero.",explicacao:"Como 0 × 0 = 0, temos √0 = 0."},
  {id:"vis-08",topico:"Produto de radicais",nivel:2,contexto:"Duas placas quadradas têm áreas de 9 m² e 16 m². Seus lados serão multiplicados para calcular uma nova medida.",pergunta:"Qual é o resultado de √9 × √16?",tipo:"duas-grades",visual:{grades:[{linhas:3,colunas:3},{linhas:4,colunas:4}]},descricao:"Duas placas quadradas: uma dividida em 9 partes e outra dividida em 16 partes.",alternativas:["12","7","25","144"],correta:"12",dica:"Descubra o lado de cada placa antes de multiplicar.",explicacao:"√9 = 3 e √16 = 4. Logo, √9 × √16 = 3 × 4 = 12."},
  {id:"vis-09",topico:"Simplificação",nivel:2,contexto:"Para simplificar √12, Pedro separou o radicando em dois fatores.",pergunta:"Qual fator pode sair do radical por possuir raiz exata?",tipo:"fatoracao",visual:{raiz:"√12",fatores:["4","3"],exato:"4"},descricao:"A raiz de 12 foi decomposta em raiz de 4 vezes raiz de 3; o fator 4 está destacado.",alternativas:["4","3","12","2"],correta:"4",dica:"Procure entre os fatores um quadrado perfeito.",explicacao:"12 = 4 × 3 e √4 = 2. Por isso, √12 = √4 × √3 = 2√3."},
  {id:"vis-10",topico:"Quociente de radicais",nivel:2,contexto:"Uma peça quadrada de área 64 cm² será comparada com outra de área 4 cm².",pergunta:"Qual é o resultado de √(64 ÷ 4)?",tipo:"expressao-simples",visual:{texto:"√(64 ÷ 4) = ?"},descricao:"Expressão raiz quadrada do quociente entre 64 e 4.",alternativas:["4","2","8","16"],correta:"4",dica:"Você pode dividir primeiro: 64 ÷ 4.",explicacao:"64 ÷ 4 = 16 e √16 = 4. Também podemos fazer √64 ÷ √4 = 8 ÷ 2 = 4."}
].map(q=>({...q,videoPergunta:VIDEO_TESTE,videoDica:VIDEO_TESTE,videoExplicacao:VIDEO_TESTE}));

let questoes=[],indice=0,pontos=0,vidas=TOTAL_VIDAS,sequencia=0,bloqueado=false,dicaUsada=false;
const el={};

document.addEventListener("DOMContentLoaded",()=>{localizar();eventos();iniciar();});
function localizar(){["pontos","questaoAtual","totalQuestoes","mapaEtapas","sequencia","topico","nivel","contexto","pergunta","cenarioVisual","descricaoCenario","alternativas","botaoDica","areaDica","textoDica","videoLibras","repetirLibras","botaoSair","botaoSairTopo","porcentagem","barra","preenchimento","vidas"].forEach(id=>el[id]=document.getElementById(id));}
function eventos(){el.botaoDica.onclick=alternarDica;el.repetirLibras.onclick=repetirVideo;el.botaoSair.onclick=confirmarSaida;el.botaoSairTopo.onclick=confirmarSaida;}
function embaralhar(lista){const c=[...lista];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;}
function iniciar(){questoes=embaralhar(questoesBase).map(q=>({...q,alternativasSorteadas:embaralhar(q.alternativas)}));indice=0;pontos=0;vidas=TOTAL_VIDAS;sequencia=0;criarMapa();mostrarQuestao();}
function criarMapa(){el.mapaEtapas.replaceChildren();questoes.forEach((_,i)=>{const li=document.createElement("li");li.dataset.numero=i+1;li.textContent="Desafio visual";el.mapaEtapas.append(li);});}
function mostrarQuestao(){const q=questoes[indice];bloqueado=false;dicaUsada=false;el.topico.textContent=q.topico.toUpperCase();el.nivel.textContent="NÍVEL "+q.nivel;el.contexto.textContent=q.contexto;el.pergunta.textContent=q.pergunta;el.descricaoCenario.textContent=q.descricao;el.cenarioVisual.setAttribute("aria-label",q.descricao);el.textoDica.textContent=q.dica;el.areaDica.hidden=true;el.botaoDica.textContent="💡 Ver dica";el.botaoDica.setAttribute("aria-expanded","false");renderizarCenario(q);criarAlternativas(q);carregarVideo(q.videoPergunta);atualizar();}
function renderizarCenario(q){const c=el.cenarioVisual;c.replaceChildren();if(q.tipo==="grade")return c.append(criarGrade(q.visual.linhas,q.visual.colunas,q.visual.tema));if(q.tipo==="duas-grades"){const caixa=document.createElement("div");caixa.className="fatoracao";q.visual.grades.forEach((g,i)=>{caixa.append(criarGrade(g.linhas,g.colunas,"azul"));if(i===0){const vezes=document.createElement("strong");vezes.textContent="×";vezes.style.fontSize="35px";caixa.append(vezes);}});return c.append(caixa);}if(q.tipo==="cubo")return c.append(criarCubo(q.visual.lado));if(q.tipo==="expressao"){const box=document.createElement("div");box.className="expressao-visual";q.visual.partes.forEach(p=>{const s=document.createElement("span");s.className="parte"+(p.destaque?" destaque":"");s.textContent=p.texto;s.dataset.label=p.rotulo;box.append(s);});return c.append(box);}if(q.tipo==="fatoracao"){const box=document.createElement("div");box.className="fatoracao";[q.visual.raiz,"=",...q.visual.fatores.flatMap((f,i)=>i?["×",`√${f}`]:[`√${f}`])].forEach(t=>{const s=document.createElement("span");s.className="bloco"+(t===`√${q.visual.exato}`?" exato":"");s.textContent=t;box.append(s);});return c.append(box);}if(q.tipo==="objetos"){const box=document.createElement("div");box.className="objetos";box.style.setProperty("--colunas",q.visual.colunas);for(let i=0;i<q.visual.quantidade;i++){const s=document.createElement("span");s.className="objeto";s.textContent=q.visual.icone;box.append(s);}return c.append(box);}const s=document.createElement("div");s.className="expressao-visual";s.textContent=q.visual.texto;c.append(s);}
function criarGrade(linhas,colunas,tema){const grade=document.createElement("div");grade.className="grade"+(tema==="azul"?" azul":"");grade.style.gridTemplateColumns=`repeat(${colunas},auto)`;for(let i=0;i<linhas*colunas;i++)grade.append(document.createElement("span"));return grade;}
function criarCubo(lado){const cubo=document.createElement("div");cubo.className="cubo";cubo.style.setProperty("--lado",Math.min(lado,4));["topo-cubo","lado-cubo","frente"].forEach(nome=>{const face=document.createElement("div");face.className=`face ${nome}`;for(let i=0;i<Math.min(lado,4)**2;i++)face.append(document.createElement("span"));cubo.append(face);});return cubo;}
function criarAlternativas(q){el.alternativas.replaceChildren();q.alternativasSorteadas.forEach((texto,i)=>{const b=document.createElement("button");b.type="button";b.className="alternativa";b.dataset.resposta=texto;b.innerHTML=`<span class="letra">${"ABCD"[i]}</span><span></span>`;b.lastElementChild.textContent=texto;b.onclick=()=>responder(texto,b);el.alternativas.append(b);});}
async function responder(escolhida,botao){if(bloqueado)return;bloqueado=true;const q=questoes[indice],acertou=escolhida===q.correta;el.alternativas.querySelectorAll("button").forEach(b=>{b.disabled=true;if(b.dataset.resposta===q.correta)b.classList.add("correta");else if(b===botao)b.classList.add("incorreta");});if(acertou){pontos+=dicaUsada?7:10;sequencia++;}else{vidas--;sequencia=0;}atualizar();await alertaResposta(acertou,q);if(vidas<=0)return finalizar(false);indice++;if(indice>=questoes.length)return finalizar(true);mostrarQuestao();}
function alternarDica(){const abrir=el.areaDica.hidden;el.areaDica.hidden=!abrir;el.botaoDica.textContent=abrir?"💡 Ocultar dica":"💡 Ver dica";el.botaoDica.setAttribute("aria-expanded",String(abrir));if(abrir)dicaUsada=true;carregarVideo(abrir?questoes[indice].videoDica:questoes[indice].videoPergunta);}
function urlVideo(url,autoplay=false){return `${url}?rel=0&modestbranding=1${autoplay?"&autoplay=1":""}`;}
function carregarVideo(url){el.videoLibras.src=urlVideo(url);}
function repetirVideo(){const q=questoes[indice],url=el.areaDica.hidden?q.videoPergunta:q.videoDica;el.videoLibras.src="";setTimeout(()=>el.videoLibras.src=urlVideo(url,true),100);}
function conteudoAlerta(texto,video,titulo){return `<div class="alerta-conteudo"><div class="texto-alerta">${texto}</div><iframe id="videoAlerta" class="video-alerta" src="${urlVideo(video)}" title="${titulo}" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><button id="repetirAlerta" class="botao-alerta-repetir" type="button">↻ Repetir tradução em Libras</button></div>`;}
function ativarAlerta(video){const v=document.getElementById("videoAlerta"),b=document.getElementById("repetirAlerta");if(v&&b)b.onclick=()=>{v.src="";setTimeout(()=>v.src=urlVideo(video,true),100);};}
async function alertaResposta(acertou,q){await Swal.fire({icon:acertou?"success":"error",title:acertou?"Muito bem!":"Vamos observar novamente",html:conteudoAlerta(q.explicacao,q.videoExplicacao,"Explicação em Libras"),confirmButtonText:"Continuar",confirmButtonColor:"#1d3557",allowOutsideClick:false,didOpen:()=>ativarAlerta(q.videoExplicacao),willClose:()=>{const v=document.getElementById("videoAlerta");if(v)v.src="";}});}
function atualizar(){el.pontos.textContent=pontos;el.questaoAtual.textContent=Math.min(indice+1,questoes.length);el.totalQuestoes.textContent=questoes.length;el.sequencia.textContent=sequencia;el.vidas.textContent="❤️".repeat(vidas);const percentual=Math.round(indice/questoes.length*100);el.porcentagem.textContent=percentual+"%";el.preenchimento.style.width=percentual+"%";el.barra.setAttribute("aria-valuenow",percentual);el.mapaEtapas.querySelectorAll("li").forEach((li,i)=>{li.classList.toggle("atual",i===indice);li.classList.toggle("concluida",i<indice);});}
async function finalizar(concluiu){el.preenchimento.style.width=concluiu?"100%":el.preenchimento.style.width;el.porcentagem.textContent=concluiu?"100%":el.porcentagem.textContent;const r=await Swal.fire({icon:concluiu?"success":"warning",title:concluiu?"Missão concluída!":"Suas vidas terminaram",html:conteudoAlerta(`Pontuação: <strong>${pontos}</strong>.<br>Este protótipo não altera o progresso da trilha.`,VIDEO_TESTE,"Resultado em Libras"),showCancelButton:true,confirmButtonText:"Jogar novamente",cancelButtonText:"Fechar protótipo",confirmButtonColor:"#1d3557",cancelButtonColor:"#5fa8d3",allowOutsideClick:false,didOpen:()=>ativarAlerta(VIDEO_TESTE)});if(r.isConfirmed)iniciar();else sairPrototipo();}
async function confirmarSaida(){const r=await Swal.fire({icon:"question",title:"Sair do protótipo?",html:conteudoAlerta("Esta partida não está associada à trilha e seu progresso não será salvo.",VIDEO_TESTE,"Saída em Libras"),showCancelButton:true,confirmButtonText:"Sim, sair",cancelButtonText:"Continuar jogando",confirmButtonColor:"#d94b4b",cancelButtonColor:"#1d3557",didOpen:()=>ativarAlerta(VIDEO_TESTE)});if(r.isConfirmed)sairPrototipo();}
function sairPrototipo(){if(history.length>1)history.back();else location.href="index.html";}